### ISSUE TITLE
BUG: attempt to index a nil value (field 'Text')

### ISSUE THREAD

**Issue by 3anz** [AnirudhG07/nbpreview.yazi#2]
Hi,

I have nbpreview installed and works with no issue in my terminal.

I installed this plugin and got the following log:

`
2024-12-08T06:15:48.162505Z ERROR yazi_plugin::isolate::peek: RuntimeError("[string \"nbpreview\"]:51: attempt to index a nil value (field 'Text')\nstack traceback:\n\t[string \"nbpreview\"]:51: in function <[string \"
       │ nbpreview\"]:3>")
 664   │     at yazi-plugin/src/isolate/peek.rs:50
`

yazi --debug:

`
Yazi
    Version: 0.3.3 (Arch Linux 2024-09-05)
    Debug  : false
    OS     : linux-x86_64 (unix)

Ya
    Version: 0.3.3 (Arch Linux 2024-09-05)

Emulator
    Emulator.via_env: ("xterm-256color", "WezTerm")
    Emulator.via_csi: Ok(WezTerm)
    Emulator.detect : WezTerm

Adapter
    Adapter.matches: Iterm2

Desktop
    XDG_SESSION_TYPE           : Some("wayland")
    WAYLAND_DISPLAY            : Some("wayland-1")
    DISPLAY                    : Some(":0")
    SWAYSOCK                   : None
    HYPRLAND_INSTANCE_SIGNATURE: Some("12f9a0d0b93f691d4d9923716557154d74777b0a_1733637801_2037818280")
    WAYFIRE_SOCKET             : None

SSH
    shared.in_ssh_connection: false

WSL
    WSL: false

Variables
    SHELL              : Some("/usr/bin/zsh")
    EDITOR             : Some("nvim")
    VISUAL             : Some("nvim")
    YAZI_FILE_ONE      : None
    YAZI_CONFIG_HOME   : None

Text Opener
    default: Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })
    block  : Some(Opener { run: "${EDITOR:-vi} \"$@\"", block: true, orphan: false, desc: "$EDITOR", for_: None, spread: true })

Multiplexers
    TMUX               : false
    tmux version       : No such file or directory (os error 2)
    ZELLIJ_SESSION_NAME: None
    Zellij version     : 0.41.2

Dependencies
    file             : 5.46
    ueberzugpp       : No such file or directory (os error 2)
    ffmpegthumbnailer: No such file or directory (os error 2)
    magick           : No such file or directory (os error 2)
    fzf              : 0.56.3
    fd               : No such file or directory (os error 2)
    rg               : 14.1.1
    chafa            : No such file or directory (os error 2)
    zoxide           : 0.9.6
    7z               : 17.05
    7zz              : No such file or directory (os error 2)
    jq               : 1.7.1
`

**Comment by AnirudhG07** [comment]
Are you using the nightly version? If no, pls try that.

**Comment by 3anz** [comment]
Appreciate the quick reply!

No, I am using the stable release (Sep 5th). I'll wait for the new release and will report back if the issue persists.

**Comment by AnirudhG07** [comment]
Congrats, new version was just released! I am updating nbpreview for yazi v0.4
It will be done by Tonight!
Thanks
